workflows:
  android-debug:
    name: Privacy WhatsApp Android Debug
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Generate Android platform files
        script: |
          cd mobile
          flutter create --platforms=android --org com.privacywhatsapp .
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get
      - name: Analyze Flutter project
        script: |
          cd mobile
          flutter analyze
      - name: Build APK
        script: |
          cd mobile
          flutter build apk --debug
    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
