import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

const red = Color(0xFFE53935);
const black = Color(0xFF080808);
const panel = Color(0xFF151515);

void main() => runApp(const PrivacyWhatsApp());

class PrivacyWhatsApp extends StatelessWidget {
  const PrivacyWhatsApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false, title:'Privacy WhatsApp', theme:ThemeData(brightness:Brightness.dark, scaffoldBackgroundColor:black, colorScheme:ColorScheme.dark(primary:red), useMaterial3:true), home:const LoginScreen());
}

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState()=>_LoginState(); }
class _LoginState extends State<LoginScreen>{
  final phone=TextEditingController(); final otp=TextEditingController(); bool sent=false;
  @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:35),Center(child:Icon(Icons.chat_bubble_rounded,size:90,color:red)),const SizedBox(height:20),const Text('Privacy WhatsApp',textAlign:TextAlign.center,style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),const Text('Private • Business • Secure',textAlign:TextAlign.center,style:TextStyle(color:Colors.white60)),const SizedBox(height:45),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Phone number',prefixText:'+92 ',filled:true,fillColor:panel,border:OutlineInputBorder())),if(sent)...[const SizedBox(height:15),TextField(controller:otp,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'OTP',filled:true,fillColor:panel,border:OutlineInputBorder()))],const SizedBox(height:20),ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:red,foregroundColor:Colors.white,padding:const EdgeInsets.all(16)),onPressed:(){if(!sent){setState(()=>sent=true);}else{Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const HomeScreen()));}},child:Text(sent?'Verify OTP':'Send OTP')),const SizedBox(height:10),const Text('Real SMS OTP provider must be connected in backend before production.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white38,fontSize:12))]))));
}

class HomeScreen extends StatefulWidget{const HomeScreen({super.key});@override State<HomeScreen> createState()=>_HomeState();}
class _HomeState extends State<HomeScreen>{int tab=0; final pages=const [ChatsScreen(),StatusScreen(),CallsScreen(),SettingsScreen()]; @override Widget build(BuildContext c)=>Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(backgroundColor:panel,indicatorColor:red.withOpacity(.25),selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble),label:'Chats'),NavigationDestination(icon:Icon(Icons.circle_outlined),selectedIcon:Icon(Icons.circle),label:'Status'),NavigationDestination(icon:Icon(Icons.call_outlined),selectedIcon:Icon(Icons.call),label:'Calls'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'Settings')]));}

class ChatsScreen extends StatelessWidget{const ChatsScreen({super.key}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Privacy WhatsApp'),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.search)),IconButton(onPressed:(){},icon:const Icon(Icons.more_vert))]),floatingActionButton:FloatingActionButton(backgroundColor:red,onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ChatScreen())),child:const Icon(Icons.add_comment)),body:ListView(children:[_chat(c,'Business Support','Welcome to Privacy WhatsApp','10:42 AM'),_chat(c,'Ali','Call me when you are free','9:18 AM'),_chat(c,'Sara','Photo','Yesterday')]),);
}
Widget _chat(BuildContext c,String n,String msg,String t)=>ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:6),leading:CircleAvatar(backgroundColor:red,child:Text(n[0])),title:Text(n,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(msg),trailing:Text(t,style:const TextStyle(color:Colors.white54)),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatScreen(name:n))));

class ChatScreen extends StatelessWidget{final String name;const ChatScreen({super.key,this.name='New Chat'});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Row(children:[CircleAvatar(backgroundColor:red,child:Text(name[0])),const SizedBox(width:10),Text(name)]),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.call)),IconButton(onPressed:(){},icon:const Icon(Icons.videocam))]),body:Column(children:[const Expanded(child:Center(child:Text('Messages will appear here'))),Container(color:panel,padding:const EdgeInsets.all(8),child:Row(children:[IconButton(onPressed:(){},icon:const Icon(Icons.attach_file)),Expanded(child:TextField(decoration:InputDecoration(hintText:'Message',filled:true,fillColor:black,border:OutlineInputBorder(borderRadius:BorderRadius.circular(25))))),IconButton(onPressed:(){},icon:const Icon(Icons.mic,color:red)),]))]));}

class StatusScreen extends StatelessWidget{const StatusScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Status')),floatingActionButton:FloatingActionButton(backgroundColor:red,onPressed:(){},child:const Icon(Icons.add)),body:ListView(children:[const ListTile(leading:CircleAvatar(backgroundColor:red,child:Icon(Icons.person)),title:Text('My status'),subtitle:Text('Tap to add status')),const Divider(),const Padding(padding:EdgeInsets.all(16),child:Text('Recent updates',style:TextStyle(color:Colors.white60))),const ListTile(leading:CircleAvatar(backgroundColor:red,child:Icon(Icons.person)),title:Text('Business update'),subtitle:Text('Today, 10:20 AM'))]));}
class CallsScreen extends StatelessWidget{const CallsScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Calls')),floatingActionButton:FloatingActionButton(backgroundColor:red,onPressed:(){},child:const Icon(Icons.add_call)),body:const Center(child:Text('Voice and video calls')));}

class SettingsScreen extends StatelessWidget{const SettingsScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Settings')),body:ListView(children:[const UserAccountsDrawerHeader(decoration:BoxDecoration(color:panel),currentAccountPicture:CircleAvatar(backgroundColor:red,child:Icon(Icons.person)),accountName:Text('Your account'),accountEmail:Text('Phone number')),const ListTile(leading:Icon(Icons.lock),title:Text('Privacy'),subtitle:Text('Last seen, profile photo, status, blocked')),const ListTile(leading:Icon(Icons.security),title:Text('Security'),subtitle:Text('Devices, sessions and alerts')),const ListTile(leading:Icon(Icons.notifications),title:Text('Notifications')),const ListTile(leading:Icon(Icons.storage),title:Text('Storage and data')),const ListTile(leading:Icon(Icons.business),title:Text('Business tools')),const ListTile(leading:Icon(Icons.report),title:Text('Help & report a problem'))]));}
